name: mini_shooter
description: Mini Shooter - A Flutter Flame V-SHMUP Game Demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  dart_minilog: ^0.0.2
  flame: ^1.17.0
  flame_tiled: ^1.20.1
  flutter_animate: ^4.5.0
  flame_audio: ^1.3.3
  stream_transform: ^2.1.0
  get: ^4.6.6
  signals_core: ^5.2.0
  rxdart: ^0.27.7
  list_operators: ^0.5.0
  kart: ^1.0.8
  collection: ^1.18.0
  supercharged: ^2.1.1
  kt_dart: ^1.1.0
  dart_extensions_methods: ^2.0.0
  audioplayers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.9

flutter:
  assets:
    - assets/audio/
    - assets/audio/background/
    - assets/audio/effect/
    - assets/fonts/
    - assets/images/
    - assets/images/fonts/
    - assets/tiles/
  shaders:
    - assets/shaders/asteroid.frag
  uses-material-design: true
